"""Couette re-validation with the symmetric CSF stencil (2026-09-02).

Re-runs the two steady-state Couette configurations of scripts/sph_validate.py
after the one-sided-curvature fix (see docs/PHASE3_CSFFIX_AUDIT.md) and persists
the full result dicts + acceptance flags. The Laplace re-calibration is
performed separately by scripts/diag_surface_tension.py (which owns that
record); the official combined validation output is regenerated by
scripts/sph_validate.py AFTER the fresh calibration lands, so its printed
Laplace section reads the new record.

Acceptance (pre-registered, mirroring the protocol):
  * R2_central > 0.99 in both configurations
  * slope_ratio_central in [0.9, 1.1] in both configurations

Run:  python scripts/rerun_couette.py
"""
from __future__ import annotations

import json
import os
import sys
from dataclasses import replace
from pathlib import Path

import numpy as np

sys.path.insert(0, os.path.join(os.path.dirname(__file__), ".."))

from tau_mech.sph import SPHParams, validate_couette  # noqa: E402

OUT = Path("outputs/sph/couette_revalidation.json")


def main():
    params = SPHParams()
    rows = {}
    configs = {
        "nu_0.5_H8": replace(params, mu_solvent=0.5),
        "nu_0.05_H4": replace(params, mu_solvent=0.05),
    }
    for name, p in configs.items():
        domain = (0.0, 0.0, 24.0, 8.0) if "H8" in name else (0.0, 0.0, 24.0, 4.0)
        # Parameter-free run-length rule: integrate to t = 3*tau (three
        # viscous decay times of the slowest mode) so EVERY configuration is
        # at steady state by construction - the previous fixed n_steps=6000
        # left nu_0.05_H4 at t/tau = 1.04, i.e. still transient, which is a
        # protocol flaw, not a solver result.
        from tau_mech.sph import _wall_lattice
        _, _, inner_bottom, inner_top = _wall_lattice(
            domain[0], domain[1], domain[2], domain[3], 0.5, 4)
        H_wall = inner_top - inner_bottom
        tau = H_wall**2 / ((p.mu_solvent / 1.0) * np.pi**2)
        n_steps = int(np.ceil(3.0 * tau / 0.008))
        r = validate_couette(p, n_steps=n_steps, dt=0.008, domain=domain)
        r["acceptance"] = {
            "r2_central_gt_0.99": bool(r["r2_central"] > 0.99),
            "slope_ratio_central_in_0.9_1.1": bool(0.9 <= r["slope_ratio_central"] <= 1.1),
        }
        r["acceptance"]["pass"] = bool(all(r["acceptance"].values()))
        rows[name] = r
        print(f"{name}: R2_fit={r['r2_fit']:.4f} R2_central={r['r2_central']:.4f} "
              f"slope_ratio_central={r['slope_ratio_central']:.4f} "
              f"slip={r['slip_frac']:.3f} pass={r['acceptance']['pass']}")
    record = {
        "solver_state": "post CSF-symmetric-stencil fix + lattice-row profile "
                        "binning (2026-09-02)",
        "protocol": "steady-state linear profile; no-slip planes = innermost "
                    "frozen wall rows; central fit excludes ~2h wall layers; "
                    "run length = 3 viscous times tau per config; y-profile "
                    "binned by exact lattice rows; slip = linear extrapolation "
                    "of the bulk fit to the no-slip planes",
        "n_steps": 6000, "dt": 0.008,
        "configs": rows,
        "all_pass": bool(all(v["acceptance"]["pass"] for v in rows.values())),
    }
    OUT.write_text(json.dumps(record, indent=2))
    print(f"saved -> {OUT}")
    print("ALL_PASS:", record["all_pass"])


if __name__ == "__main__":
    main()
